/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_YHJstyle_b005_jump_EcgNative */

#ifndef _Included_com_YHJstyle_b005_jump_EcgNative
#define _Included_com_YHJstyle_b005_jump_EcgNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_YHJstyle_b005_jump_EcgNative
 * Method:    EcgIni
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_YHJstyle_b005_jump_EcgNative_EcgIni
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_YHJstyle_b005_jump_EcgNative
 * Method:    EcgInserData
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_com_YHJstyle_b005_jump_EcgNative_EcgInserData
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_YHJstyle_b005_jump_EcgNative
 * Method:    EcgProcessData
 * Signature: ([S[S)I
 */
JNIEXPORT jint JNICALL Java_com_YHJstyle_b005_jump_EcgNative_EcgProcessData
  (JNIEnv *, jobject, jshortArray, jshortArray);

/*
 * Class:     com_YHJstyle_b005_jump_EcgNative
 * Method:    EcgProcessDebug
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_YHJstyle_b005_jump_EcgNative_EcgProcessDebug
  (JNIEnv *, jobject);

/*
 * Class:     com_YHJstyle_b005_jump_EcgNative
 * Method:    TestCalTime
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_YHJstyle_b005_jump_EcgNative_TestCalTime
  (JNIEnv *, jclass);
extern int InsertData(unsigned short dat);

extern signed char ecg_hb(unsigned char *db,short *pdata);

extern void ecg_init(unsigned int PowerFreq);

extern void StartDetect(unsigned short Second);

extern void GetAnalyseResultA(signed char * pExceptionFlag);

extern unsigned short GetExceptionData(int abNormalID,unsigned short pIndx[],
		unsigned short * pNumbers);

extern void GetVString (signed char * ps);
#ifdef __cplusplus
}
#endif
#endif
